### ISSUE TITLE
Example usage is broken

### ISSUE THREAD

**Issue by jessefeinman** [hashicorp/terraform-schema#224]
https://github.com/hashicorp/terraform-schema#usage

In the example usage it shows a simple 3 step way to merge the core schema with a schema from a json file. It appears that these functions no longer exist and there's no examples for how to straightforwardly merge 2 schemas anymore.

Can the example be updated to show how to do this again?

**Comment by dbanck** [comment]
Hi @jessefeinman 
Thanks for the report. We're already tracking this under #153, so I'll close this as a duplicate.
