### ISSUE TITLE
(output) Unexpected block: Blocks of type "precondition" are not expected here

### ISSUE THREAD

**Issue by nickesk** [hashicorp/terraform-schema#280]
I have the following `output` block:

```terraform
output "__validation" {
  value = null
  precondition {
    condition = true
    error_message = "This is never an error"
  }
}
```

According to [the Terraform documentation](https://developer.hashicorp.com/terraform/language/expressions/custom-conditions#outputs), a `precondition` block is valid within an `output` block.

However, with HashiCorp Terraform VSCode extension v2.28.1, this produces the following error:
```
Unexpected block: Blocks of type "precondition" are not expected here
```

**Comment by radeksimko** [comment]
Great catch, thanks for the report @nickesk 

It looks like this piece of schema was already added but in the wrong shape. For some reason in https://github.com/hashicorp/terraform-schema/pull/123 I assumed that the preconditions are nested under `lifecycle`, just like they are in resources, but that's clearly not the case.

I will raise a PR with a fix.

**Comment by dbanck** [comment]
A new version [2.28.2](https://github.com/hashicorp/vscode-terraform/releases/tag/v2.28.2) was just released. This fixes the reported bug. The update should appear automatically in VS Code.

--- 

In case you experience any different validation related bug, please do let us know through a new issue.
