### ISSUE TITLE
schema: Conclude `module_variable_optional_attrs` language experiment (v1.8)

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-schema#328]
See https://github.com/hashicorp/terraform/pull/34752

https://github.com/hashicorp/terraform-schema/blob/1ed5c20752222b891f5985a46e650ac852283525/internal/schema/0.14/terraform.go#L31-L34

I would also recommend reviewing experiments in general, to check they actually align with core.

**Comment by apparentlymart** [comment]
Given that the whole point of language experiments is that they be lightweight to add, remove, and conclude, I would suggest that this repository probably shouldn't try to mirror the list of them, and instead tools should consider the `experiments` argument as just a static list of arbitrary identifiers, leaving Terraform Core to check whether they are valid.

Given how short-lived some experiments tend to be, it seems like overkill to try to do autocomplete and semantic checking for individual experiment keywords. Having to update the schema for every single lifecycle change of every single experiment seems like it would either cause this set to always be constantly outdated (the current situation) or cause teams to waste time trying to carefully chase changes to a very-marginally-used part of the language that is never valid in stable releases anyway.
