### ISSUE TITLE
schema: Introduce provisioners to `removed` blocks for Terraform 1.9

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-schema#329]
Currently a draft but might land in 1.8 https://github.com/hashicorp/terraform/pull/34753

**Comment by dbanck** [comment]
Since it is still a draft and an RC for 1.8 has been released, is it safe to assume that it will not ship with 1.8?

**Comment by radeksimko** [comment]
@dbanck This is remaining a draft, not expected to land in 1.8

**Comment by radeksimko** [comment]
https://github.com/hashicorp/terraform/pull/35230 (most likely to land in 1.9)

**Comment by kmoe** [comment]
https://github.com/hashicorp/terraform/pull/35230 is merged and released in v1.9.0-beta1.
