### ISSUE TITLE
schema: New functions `tfvarsencode`, `tfvarsdecode` and `exprencode` (v1.8)

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-schema#330]
See https://github.com/hashicorp/terraform/pull/34718

Worth noting these are actually `terraform` provider namespaced functions, unlike the existing core functions.

**Comment by dbanck** [comment]
We support these functions when the built-in Terraform provider is declared in the `required_providers` block. This is the preferred way to use these functions, as stated in the docs: https://developer.hashicorp.com/terraform/language/v1.8.x/functions/terraform-encode_tfvars

I raised https://github.com/hashicorp/terraform/pull/34891 to add descriptions for all the functions.

Today, we don't implicitly load a provider schema when you add a namespaced function to your configuration, so declaring the provider first, is the preferred way for functions.

I've checked that everything works as expected, so I'm closing the issue as complete.
